### PR TITLE
SCMOD-12630: Add banDuplicatePomDependencyVersions

### PR DESCRIPTION
**Pull request by xbreizh**
https://portal.digitalsafe.net/browse/SCMOD-12630

### CODE REVIEW

**Review by dermot-hardy — COMMENTED** [review]
Also update the execution id given this change.

**Comment by xbreizh** [comment]
@dermot-hardy I updated the execution id here to match both actions, but shouldn't we use a separate execution that would always be true instead of having it depending on the enforce-banned-dependencies that can be disabled in some cases and leave the build pass?

**Review by dermot-hardy — CHANGES_REQUESTED** [review]
Yes that's a fair point.  Having this triggered by an `enforceBannedDependencies` flag makes no sense.

**Review by dermot-hardy — APPROVED** [review]
You know what, I changed my mind.  It's just a matter of perspective.  We can just say that duplicate dependencies are banned.  I'd even put the execution id back to what it was before.

**Pull request merged**
